In [1]:
import requests
import pandas as pd
import time
from urllib.parse import quote

In [ ]:
API_KEY = "HDEV-907006be-6b96-44d1-bff6-ade257f217ff"
headers = {"Authorization": API_KEY}
BASE = "https://api.henrikdev.xyz/valorant"
regions = ["eu", "na", "latam", "br", "ap", "kr"]

for region in regions:
    players_list = []
    url = f"{BASE}/v3/leaderboard/{region}/pc?size=6000"
    r = requests.get(url, headers=headers)
    data = r.json()

    players = data["data"]["players"]   
    for p in players:
        players_list.append({
            "name": p["name"],       
            "tag": p["tag"],
            "region": region,
            "rr": p["rr"],
            "rank": p["leaderboard_rank"],
            "puuid": p["puuid"]
        })

    print(f"{region} collected")
    players_df = pd.DataFrame(players_list)
    players_df.to_csv(f"players_{region}.csv", index=False)
    print(f"CSV for {region} saved")

    time.sleep(3)

eu collected
CSV for eu saved
na collected
CSV for na saved
latam collected
CSV for latam saved
br collected
CSV for br saved
ap collected
CSV for ap saved
kr collected
CSV for kr saved

In [2]:
korean_players_df = pd.read_csv('players_kr.csv').dropna()
display(korean_players_df)
european_players_df = pd.read_csv('players_eu.csv').dropna()
display(european_players_df)
br_players_df = pd.read_csv('players_br.csv').dropna()
display(br_players_df)
latam_players_df = pd.read_csv('players_latam.csv').dropna()
display(latam_players_df)
ap_players_df = pd.read_csv('players_ap.csv').dropna()
display(ap_players_df)
na_players_df = pd.read_csv('players_na.csv').dropna()
display(na_players_df)

,name,tag,region,rr,rank,puuid
2,StreN,1111,kr,476,3,b2f590ab-9075-5ad3-aeec-07085aab1083
3,High sens is OP,00000,kr,474,4,22ba8ce6-d128-5399-a3d4-954811a05ab2
6,우 유,한국인,kr,410,7,8e5e5ad9-b746-5c4f-9ad3-629a59d4af10
7,마토이 류코,纏 流子,kr,406,8,2dd9302b-62f1-5270-adaf-4b5b40db2472
8,MIBR zekken,다운증후군,kr,402,9,0fe2a10b-2e61-5c29-b17d-a362c3cd5149
...,...,...,...,...,...,...
2994,그만할게요,나 이거,kr,0,2995,a1abb513-3f97-5fc3-bbd8-4ae5e53d6071
2995,하리보가슴,내꺼야,kr,0,2996,d0e68071-1cc8-5ce4-982d-1c1bbe93eb3f
2996,김문혁일병구하기,0630,kr,0,2997,5c9362ab-261d-5c98-84de-ae3a9f195608
2998,순대 JMT,4068,kr,0,2999,0050009b-1b94-5955-8e47-a7b009e232d6
2999,탱크보이 오하준,518광주,kr,0,3000,5c49a127-cc9c-5340-a720-f1efbe925dee

,name,tag,region,rr,rank,puuid
1,TH Wo0t,Limon,eu,949,2,b48f11cc-6264-5ac1-bc59-70f46620f7a5
2,SGE Jamelinho,213,eu,928,3,ef505d70-cd68-5dd5-9adb-6aa6068397ad
3,MercureFPS,GRIND,eu,878,4,7ecd6566-cc89-5f06-856e-0f59ccf682d2
5,MDR nataNk,1wnl,eu,858,6,8fbbea9d-1366-5eab-be2e-765355452d56
6,izana,686,eu,856,7,b800c119-8ab3-5113-97cd-d2a636e93f6e
...,...,...,...,...,...,...
5992,Lingling,ODIN,eu,116,5993,1f092510-562d-53a8-b761-e9db03fcf981
5993,ASSUrdo,bb1,eu,116,5994,ba80a479-a650-51d7-9c73-074e2f6237b6
5995,Nero,Wonx,eu,116,5996,d113ac06-13b7-539c-9a16-391ae5d2eefc
5997,VirusPayal,UwU,eu,116,5998,269b2b3a-b596-533a-a4f3-06df6ae51f9a
5999,Данил Колбасенко,xxxxx,eu,116,6000,b8daecb0-bbb3-5890-b2d2-28eefc3ecfa9

,name,tag,region,rr,rank,puuid
0,F4T znajder99,2009,br,963,1,bad04337-c99d-5be8-83df-ffb0a2e59365
1,PSC raised,εγώ,br,821,2,87a6fa2e-2f15-5460-94f2-7df1d0d4a187
2,INTZ Palla,carol,br,779,3,b6cb2c53-090e-543e-9bc3-8d1d4eb62217
3,2G BRKSS3,2000,br,776,4,742b9641-c312-54c4-899a-cc2e157dd0ab
4,jzn,god,br,760,5,c90dcb99-d7bc-533e-a6e2-32f1cccdba78
...,...,...,...,...,...,...
4994,ryuki luna,emipê,br,0,4995,aa18342b-5dd4-53ad-a4b7-d4243591fabf
4995,rodboyyy,BR2,br,0,4996,e48fcf4c-8590-5193-9276-84b48bffdf49
4996,the honored one,creep,br,0,4997,a5215d9f-bbcc-58be-881b-160e28515c8a
4997,All The Stars,kndrk,br,0,4998,9ff01b6f-3b27-56c9-91bc-814ec5938a2d
4998,elsewhere,eee,br,0,4999,50a148f8-0b96-5aa5-8a00-2b02181b7729

,name,tag,region,rr,rank,puuid
1,LEV Neon,1111,latam,753,2,68ae99f4-552a-5b0f-a361-2662019e42a1
2,LEV blowz,1111,latam,746,3,712421ec-81ec-5654-a2eb-c6a130d1e8bd
3,dfn,bryzz,latam,676,4,7a7509b2-23f8-5000-916a-e6f991dcfbac
4,Matiaul,6767,latam,637,5,1c3637a1-2554-5d3a-93ef-a29f63e726f2
5,Twitch matikhz,ama,latam,579,6,4ea619d2-d52e-5832-ac70-c96a40e2527d
...,...,...,...,...,...,...
3992,Arthur Leywin,Deus,latam,0,3993,c3d8606e-63f7-5fe7-b627-8cd3abe3f799
3994,Jun,JRG,latam,0,3995,0d4a1c3c-37d5-5859-96d7-1520623629c9
3995,Ramzes,YZFR3,latam,0,3996,5746def9-c268-52f6-8d5b-73577e122f1d
3996,RamZ ﾒ,Zenin,latam,0,3997,72392eb3-83f0-55eb-88ac-d2c20b2e0407
3999,neyy,123,latam,0,4000,1f827001-3d2e-55da-9332-2b132e9a053f

,name,tag,region,rr,rank,puuid
0,snappyคาบบ,XGOD,ap,976,1,e6c54b3f-43de-509a-86c8-cd9d9cad4dec
1,T1 Satoru,DDONG,ap,928,2,f4bf27fb-6597-55db-a2ec-1ed39d3c137f
2,FranK,马年大吉,ap,906,3,ddf0996e-dc6b-5004-a9cf-b70071aba180
3,Horhe,27000,ap,888,4,ddfa2090-2995-5977-a4ca-fefb281edb9b
4,Road to 1000RR,WIN,ap,873,5,74b09014-fa71-56d5-8692-c74f42041b14
...,...,...,...,...,...,...
5992,Addicted to you,FWC,ap,104,5993,1855648e-fa5b-58c8-a859-55db0bf781f9
5995,nek0solowin,mook,ap,103,5996,7e70f416-6c2c-5fbe-b53e-39620ecb59f2
5996,ZX Jung,1004,ap,103,5997,6af6910d-b80f-5b47-82d1-1d5a16ceda25
5997,エスカルゴ,AP05,ap,103,5998,588f60ce-095f-5108-834e-58af772e7cac
5999,tess,yuki,ap,103,6000,4e3eaf80-cf34-557e-9363-ed55b6e93499

,name,tag,region,rr,rank,puuid
0,twitch haeyoday,hyd,na,837,1,3e70ac37-994b-5b2a-91cf-3ee8695b87f3
1,SR exa,VIC,na,834,2,8136bfd3-f949-58dc-abec-96761066b150
2,ttv picklespear,dan,na,815,3,6d8d2524-b5a8-51b7-9969-6b360b7067d6
3,SEN nightz,aim,na,752,4,3fac8da3-1ca7-5abe-be63-10eb0e985a3b
4,Rei Hino,lft,na,750,5,a260f204-a5dd-5f0a-95f8-174cc713613c
...,...,...,...,...,...,...
5995,notime4hoes,22y,na,16,5996,bf75cf55-2d1c-5f27-8c85-cb12ccb96e56
5996,NIGHTCORE,CHUU,na,16,5997,e9aa7e96-298a-5871-9a6e-802012174163
5997,Shamm,2334,na,16,5998,e83ec452-34f7-5243-babf-41fc3b494bd4
5998,Ragefactor,Six,na,16,5999,45324f3e-99d0-5675-b1a5-6d41c6b37296
5999,Plague,00009,na,16,6000,d27cdc76-ac26-5398-8798-0409e122cfa5

In [7]:
files = [
    korean_players_df,
    european_players_df,
    latam_players_df,
    br_players_df,
    ap_players_df,
    na_players_df
]

all_players_df = pd.concat(files,ignore_index=True)
all_players_df.to_csv("players_pool.csv", index=False)
print("CSV saved")

CSV saved

In [5]:
all_players_df = pd.read_csv("players_pool.csv")
all_players_df.head()

,name,tag,region,rr,rank,puuid
0,StreN,1111,kr,476,3,b2f590ab-9075-5ad3-aeec-07085aab1083
1,High sens is OP,00000,kr,474,4,22ba8ce6-d128-5399-a3d4-954811a05ab2
2,우 유,한국인,kr,410,7,8e5e5ad9-b746-5c4f-9ad3-629a59d4af10
3,마토이 류코,纏 流子,kr,406,8,2dd9302b-62f1-5270-adaf-4b5b40db2472
4,MIBR zekken,다운증후군,kr,402,9,0fe2a10b-2e61-5c29-b17d-a362c3cd5149